apiVersion: apps/v1
kind: Deployment
metadata:
  name: phptest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phptest
  template:
    metadata:
      annotations:
        resource.opentelemetry.io/service.name: "phptest"
        profiles.grafana.com/php.enabled: "true"
      labels:
        app: phptest
    spec:
      containers:
      - name: phptest
        image: alainpham/phptest
        imagePullPolicy: "Always"
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: APPLICATION_NAME
            value: phptest
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: http/protobuf
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://grafana-k8s-monitoring-alloy-receiver.default.svc.cluster.local:4318
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: "service.name=phptest,service.namespace=$(POD_NAMESPACE),service.instance.id=$(POD_NAME),service.version=1.0.0"
        ports:
          - containerPort: 8080
          - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8081
          initialDelaySeconds: 0
          successThreshold: 1
          periodSeconds: 10
          failureThreshold: 40 
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
          initialDelaySeconds: 0
          successThreshold: 1
          periodSeconds: 10
          failureThreshold: 40 