#!/bin/bash
helm repo add grafana https://grafana.github.io/helm-charts &&
  helm repo update &&
  helm upgrade --install --atomic --timeout 300s grafana-k8s-monitoring grafana/k8s-monitoring \
    --namespace "default" --create-namespace --values - <<EOF
cluster:
  name: codersandbox.com
destinations:
  - name: grafana-cloud-metrics
    type: prometheus
    url: ${PROM_URL}/api/prom/push
    auth:
      type: basic
      username: "${PROM_USER}"
      password: $PROM_PASSWORD
  - name: grafana-cloud-logs
    type: loki
    url: ${LOKI_URL}/loki/api/v1/push
    auth:
      type: basic
      username: "${LOKI_USER}"
      password: $LOKI_PASSWORD
  - name: grafana-cloud-otlp-endpoint
    type: otlp
    url: ${OTLP_URL}/otlp
    protocol: http
    auth:
      type: basic
      username: "${OTLP_USER}"
      password: $OTLP_PASSWORD
    metrics:
      enabled: true
    logs:
      enabled: true
    traces:
      enabled: true
  - name: grafana-cloud-profiles
    type: pyroscope
    url: ${PROFILES_URL}
    auth:
      type: basic
      username: "${PROFILES_USER}"
      password: $PROFILES_PASSWORD
clusterMetrics:
  enabled: true
  opencost:
    enabled: true
    metricsSource: grafana-cloud-metrics
    opencost:
      exporter:
        defaultClusterId: codersandbox.com
      prometheus:
        existingSecretName: grafana-cloud-metrics-grafana-k8s-monitoring
        external:
          url: ${PROM_URL}/api/prom
  kepler:
    enabled: true
annotationAutodiscovery:
  enabled: true
clusterEvents:
  enabled: true
nodeLogs:
  enabled: true
podLogs:
  enabled: true
applicationObservability:
  enabled: true
  receivers:
    otlp:
      grpc:
        enabled: true
        port: 4317
      http:
        enabled: true
        port: 4318
    zipkin:
      enabled: true
      port: 9411
  connectors:
    grafanaCloudMetrics:
      enabled: true
autoInstrumentation:
  enabled: true
  beyla:
    config:
      data:
        discovery:
          services:
            - k8s_namespace: apps
profiling:
  enabled: true
  ebpf:
    enabled: true
    namespaces:
      - apps
  java:
    enabled: true
    namespaces:
      - apps
  pprof:
    enabled: false
integrations:
  alloy:
    instances:
      - name: alloy
        labelSelectors:
          app.kubernetes.io/name:
            - alloy-metrics
            - alloy-singleton
            - alloy-logs
            - alloy-receiver
            - alloy-profiles
alloy-metrics:
  enabled: true
alloy-singleton:
  enabled: true
alloy-logs:
  enabled: true
alloy-receiver:
  enabled: true
  alloy:
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP
      - name: zipkin
        port: 9411
        targetPort: 9411
        protocol: TCP
alloy-profiles:
  enabled: true
  image:
    tag: v1.11.0
EOF